rsi_period: 11
session_volume_threshold:
  opening: 0.66
  midday: 0.74
  closing: 0.66
vwap_stop_loss_pct: 0.64
ema_micro_fast_period: 9
ema_micro_slow_period: 21
long_rsi_entry: 59
long_rsi_exit: 75
short_rsi_entry: 39
short_rsi_exit: 32
vwma_macro_slow_key: 45
vwma_macro_fast_key: 21