rsi_period: 12
session_volume_threshold:
  opening: 0.64
  midday: 0.7
  closing: 0.64
vwap_stop_loss_pct: 0.48
ema_micro_fast_period: 9
ema_micro_slow_period: 21
long_rsi_entry: 56
long_rsi_exit: 73
short_rsi_entry: 42
short_rsi_exit: 34
vwma_macro_slow_key: 45
vwma_macro_fast_key: 21
